version: '3.9'

services:
  redis:
    image: redis:7.2-alpine
    container_name: meeting-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - meeting-network
  postgres:
    image: postgres:16
    container_name: meeting-postgres
    environment:
      POSTGRES_DB: meetingplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: meeting-keycloak
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/meetingplatform
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 123456
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  livekit:
    image: livekit/livekit-server:latest
    container_name: meeting-livekit
    restart: always
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50010:50000-50010/udp"
    # Dùng lệnh này để cấu hình trực tiếp, không cần file bên ngoài
    command:
      - --dev
      - --node-ip
      - 0.0.0.0
      - --keys
      - "livekit_api_key_2026: livekit_api_secret_2026_super_secure"
    networks:
      - meeting-network

  coturn:
    image: coturn/coturn:latest
    container_name: meeting-coturn
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-49160:49152-49160/udp"
    command:
      - -n --min-port=49152 --max-port=49160
      - --realm=meeting.manhduc --user=ducit:ducpass123
networks:
  meeting-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data: